nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://127.0.0.1:8080','%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS',HEAD, 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Origin','Accept', 'Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
