vich_uploader:
    db_driver: orm

    mappings:
        file_object:
            uri_prefix: /arrivageFiles
            upload_destination: '%kernel.project_dir%/datafiles/files'
            # Will rename uploaded files using a uniqueid as a prefix.
            # namer: Vich\UploaderBundle\Naming\OrignameNamer
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
